version: "3.7"

services:
  resource-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: resource_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  song-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: song_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
